# Generated by Django 2.1 on 2018-11-05 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_points_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='accountNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='account_no'),
        ),
        migrations.AlterField(
            model_name='points',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernames', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
